name: Autograding Tests

on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Run tests
      run: mvn test
      
    - name: Store test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/**/*.xml

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: |
          - id: maven-tests
            test-name: "Maven Tests"
            command: "mvn test"
            comparison-method: exact
            timeout: 300
      env:
        MAVEN_TEST_RESULTS: "${{ steps.maven-tests.outputs.result }}"